### ISSUE TITLE
[OTHER] Discussions are not enabled

### ISSUE THREAD

**Issue by Panquesito7** [krshoss/linkfree-recipes#1]
### Description

The readme file links to the discussions tab, which is disabled, thus, leading to a 404 page.
You might want to enable the discussions tab to prevent that or remove it from the readme.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshoss/linkfree-recipes/blob/main/CODE_OF_CONDUCT.md)

**Comment by krshkun** [comment]
Thank you, Enabled
