### ISSUE TITLE
[Docs]: Update GitHub Help link

### ISSUE THREAD

**Issue by Panquesito7** [krshoss/linkfree-recipes#7]
### Description

A [GitHub Help](https://help.github.com) (which is now [GitHub Docs](https://docs.github.com)) link is specified in the contributing guidelines file.
You're still being redirected, but it is best to always use the latest links, as one or another may redirect to a 404 page.

_Steps to contribute_

1. [Fork](https://github.com/krshoss/linkfree-recipes) the repository.
2. Create a new branch named `update_github_link`.
3. Open the `CONTRIBUTING.md` file.
4. In line 72, replace the GitHub Help link with the following link:

```markdown
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
```

5. Commit and push your changes.
6. Create a [pull request](https://github.com/krshoss/linkfree-recipes/compare) to compare the changes.
7. You're done now! 🎉 You just have to wait until a maintainer reviews your PR.

If you need any help with this, let us know! 🙂

### Anything else?

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshoss/linkfree-recipes/blob/main/CODE_OF_CONDUCT.md)

**Comment by krshkun** [comment]
Thanks for checking this out David 👍
